# mysql 个性化配置， 不同的环境，需要配置不同的链接信息，只需要将这段信息复制到具体环境的配置文件中进行修改即可
# 如：复制到mysql.yml中将数据库名和ip改掉
jxrory:
  mysql:
    ip: 127.0.0.1
    port: 3306
    driverClassName: com.mysql.cj.jdbc.Driver
    database: jxrory_cloud
    username: root
    password: c9ReTv4T96SGcVe
    url: jdbc:mysql://${jxrory.mysql.ip}:${jxrory.mysql.port}/${jxrory.mysql.database}?characterEncoding=utf8&useUnicode=true&useSSL=false&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true

# mysql 通用配置
spring:
  datasource:
    driverClass: com.mysql.cj.jdbc.Driver
    url: ${jxrory.mysql.url}
    username: ${jxrory.mysql.username}
    password: ${jxrory.mysql.password}

mybatis-plus:
  mapper-locations:
    - classpath*:mapper_**/**/*Mapper.xml
  # 实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.jxrory.*.entity;com.jxrory.database.mybatis.typehandler
  typeEnumsPackage: com.jxrory.*.enumeration
  global-config:
    db-config:
      id-type: INPUT
      insert-strategy: NOT_NULL
      update-strategy: NOT_NULL
      select-strategy: NOT_EMPTY
